name: OrangeHRM Regression

on:
  push:
    branches:
      - slack-integration

  workflow_dispatch:
    inputs:
      environment:
        description: "Select Environment"
        required: true
        default: qa
        type: choice
        options:
          - qa
          - dev
          - uat
          - prod

      notifySlack:
        description: "Notify Slack"
        required: true
        default: true
        type: boolean

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  regression:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        if: always()
        uses: actions/configure-pages@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Automation
        run: npm run ${{ github.event.inputs.environment }}:headless

      - name: Generate Allure Report
        if: always()
        run: |
          npx allure generate allure-results --clean -o allure-report

      - name: Upload GitHub Pages Artifact
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./allure-report

      - name: Deploy GitHub Pages
        if: always()
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Notify Slack
        if: always() && github.event.inputs.notifySlack == 'true'

        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

          GITHUB_SERVER_URL: ${{ github.server_url }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
          GITHUB_ACTOR: ${{ github.actor }}

        run: npm run notify:slack